language: node_js
node_js:
- '5'
notifications:
  slack:
    room:
      secure: GARMYcugZ97bw/BdxjoxsWoHsiehbn1GHysqWRJCOe21Sms2WoGBI6c4hmWnEaOiO/RNsaeqhLU5bPZ46gv+CGH0G1+uYpasJfEey4xmQAu2YPK4RNyq+ELuzIT8XH59Sl7IK/aRMCNJtVM+AAaknh1GwVPTDhyu8o5hZ4lurC0pNHwM8fRPk5OFB6n2dC6dSyWdmCkO1AMnoE6FTYX2M+5UhGmbnFG/BuW8AO1ypvM5grJyY5MFi27azfvHhWP81CEvDRERAVI7Y0nB9Zv9W9+/g4y+eXUWiRzMZsbzc1+4Mnp/iaQSEjN/HeOfo0DnlXtwpO+hcW2zutSlEYch9wLzXQaYuzH3Ew57Hwq5Ws/mNKExPglUihExl/JOCM8ikyN7QP7zOx3/uJCM41SzaV5t0tKlg8iZ0rJpwkn5E3FkFSiUvTRfI1oDBiuSWioPxRQC6t5xG9zCCgJp3Ct1Y9h76s/VZyN2aLUB4/B3VFtsyxwb43henbn0FXXe299QsJtaNgTGRTC+F+Vig1r8RwbK3jrckHgdWPcENKDoq14kb4R25dlZ+YgmT4fDYPRQO9g3OCnjwqF4KDL1VLh9EWFcwfj4X8y5S0Q+aoIiftS/KUYBaLv9giLTF8JZNfUQGUr9EpmGPSUia16Iho6bR6ISJSvjIQuoLIYXqJ+8tL4=
  email: false
