language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: yenvMQIOEcSUOAxaCCGGKg8eiHZzCSYDkLU80VAOXZNkAoqPoJ/MxSmUSA/elWm/hZ8bIzzbfRf2j4OZjsjzeRIywlI0XLmo7Ix/khXYknVxm929oGOm1zysQ195AXB2b/4rmqth7vOp9oUTvClHiykNik/aMbgt9M9QgaOPMXEnROoxrZb0dBQRT4aXegQF7G81O62e6hcaJVI2YrG9kVuvQBx4DHB2JRKTae6Nbs/7kp7gFfKB0GdMH7gGUUkKjtB5KhlZyyZWndIz1g131X8MOZzYoXgIVcr8toOxhNmppPUwMXBulKnnTkBr0FBNtCcRcxGPk97G7Xqn6EzEXhGE2AwnRlDpFJ8fDOsLhgr+EsXG1njl6NfpC73hsPzXUdqf1EU9+PhzCukaR9K5anE05r0OgIlOLTCReYLhN5icL2+5FLlNszD+dV13CNJvgBv6VY7+5rIsLSikPaIeUz3V3jcTs68gA148BqWH1OZMobf6UVkJa6/aeEd9aclR8rikMWaZ9ChjONAZFgx0wAmwKVOeKGRwbqQ0wgCDCLGnOMZFs01gxfMBjPFKN3x4cOi6YS6gCZmXBNT55wBNqqwaTNl1Gqzs/tGPeplG0GYDCY4Fky0MH03HgIirzcBotUcOW3fHVSE3b9uBLpRRZvi6B6PGsEpdlPS6OkOoHic=
  email: false
