language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: E68x/fX00s34CltdUGmJPPCjIYT3l1UJuxPw5JwQkMKUcTtSJ0RkLQKa5jkbXmDJmnScqtMIA5SVeq84z3m+hgNd8mPA2XGyzUzAT1mhORHT2xuhU823EyZ146XuXm2cybfXFFIIR3dHyfhP9f4TA3k9dsZG8PG9CgS9KCpodzLseiOoNgM6bMxkQBQTDZe4vrOpiWSKb6CxAKF44WWEhdNacIVEbUihWdCDg4gocneHJyN7G3sBHkTU5Yi4canZmC6HisgaQmO+D/MSiKphQInMbF9LlQk+zsviOSHOzM3kl4ZL+TeMS1yX9LYLe4udWCZPnKhHPMj/LQhmSz2uOo/+CzW3UDiJuLXmPvZbyNnVJVlyGGVZJEaO4RlXV2ZxuANGvoNgTR93/M4hTWObbsGZARVIRJFkj7Gson1CfV2q36XMTfgLMa6KndQl8qAOyCTtdBtf6ptidgNDmX+cXySxkTbaDBEMTvEXyByGw+NiK56qgJkg0+04+jYfXEEE3Vx+HeEgNQtkJ1EpcQ2Plo4UT2v6fdE7Wex/RDhGheIJgySofXvAJ873159rS+O5icGFwyAVMs1yjp3i0EU6svrGSAoTn+kNamUCYdZBGFjfgKDcNydgk6pUOfz8HO+2m7ksvIPJCaGCjziYehtQzUDQj5iNdIE8wOtMX5cUhNk=
  email: false
